---
version: "2.1"
services:
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      - GID=1000
      - COLLECTIONS=crowdsecurity/nginx crowdsecurity/http-cve crowdsecurity/whitelist-good-actors
      - CUSTOM_HOSTNAME=bitwar.grasfer.com
    volumes:
      - /opt/appdata/crowdsec/config:/etc/crowdsec:rw
      - /opt/appdata/crowdsec/data:/var/lib/crowdsec/data:rw
      - /opt/appdata/swag/log/nginx:/var/log/swag:ro
      - /var/log:/var/log/host:ro
    networks:
      - lsio
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - URL=scaredofgirls.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=grasferserver@protonmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-crowdsec
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
    volumes:
      - /home/grasfer/docker/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    networks:
      - lsio
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=smtp.fastmail.com
      - SMTP_FROM=grasferserver@fastmail.com
      - SMTP_PORT=465
      - SMTP_SECURITY=force_tls
      - SMTP_USERNAME=grasfer@fastmail.com
      - SMTP_PASSWORD=${BITWAR_EMAIL_PASS}
#      - ADMIN_TOKEN=${BITWAR_ADMIN_TOKEN}
      - DISABLE_ADMIN_TOKEN=true
    volumes:
      - /home/grasfer/docker/vaultwarden:/data
    networks:
      - lsio

networks:
  lsio:
    external: true
  default:
    name: lsio
    external: true
